server:
  port: 8080
eureka:
  instance:
    hostname: orders
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: orders
  data:
    mongodb:
      uri: mongodb://mongo:27017/orders
  kafka:
    bootstrap-servers: kafka:9092
    topic:
      accounts-customer: accounts.customer.change
      orders-order: orders.order.fulfill
      fulfillment-order: fulfillment.order.change
    consumer:
      group-id: orders
      auto-offset-reset: earliest
  zipkin:
    sender:
      type: kafka
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: INFO
---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/orders
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8090
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: DEBUG
---
spring:
  config:
    activate:
      on-profile: confluent
server:
  port: 8080
logging:
  level:
    root: INFO
